kind: ConfigMap
apiVersion: v1
metadata:
  name: collections
data:
  collections.json: |-
    {
      "collections":
        [
          {"name":"collection_1","display_name":"Collection 1"},
          {"name":"collection_2","display_name":"Collection 2"}
        ]
    }